export const mockPostcards = [
  {
    id: 1,
    sentByMe: false,
    countryName: "Japan",
    location: "Tokyo, Japan",
    latitude: 35.6762,
    longitude: 139.6503,
    greeting: "Konnichiwa!",
    text: "The city is absolutely incredible – neon lights everywhere and the food is beyond amazing. I wish you were here to experience all of this with me!",
    image: "https://example.com/images/tokyo.jpg",
    createdAt: new Date("2024-11-10T14:23:00Z"),
    questId: 3,
    xp: 50,
    receiverAddress: { street: "Musterstraße 1", city: "Berlin", zip: "10115" },
  },
  {
    id: 2,
    sentByMe: true,
    countryName: "Portugal",
    location: "Lissabon, Portugal",
    latitude: 38.7169,
    longitude: -9.1395,
    greeting: "Olá!",
    text: "The tram ride up to the castle is something truly special. Having Pastéis de nata every single morning – I might just never come back home again.",
    image: "https://example.com/images/lisbon.jpg",
    createdAt: new Date("2024-12-01T09:10:00Z"),
    questId: null,
    xp: 30,
    receiverAddress: { street: "Hauptweg 9", city: "München", zip: "80331" },
  },
  {
    id: 3,
    sentByMe: false,
    countryName: "Australien",
    location: "Sydney, Australien",
    latitude: -33.8688,
    longitude: 151.2093,
    greeting: "G'day!",
    text: "I saw my first kangaroo in the wild today, it was surreal. The Opera House is even more breathtaking in person than it ever looked in any photo.",
    image: "https://example.com/images/sydney.jpg",
    createdAt: new Date("2025-01-15T18:45:00Z"),
    questId: 7,
    xp: 75,
    receiverAddress: null,
  },
];
