export const mockPostcards = [
  {
    id: 1,
    creatorId: "2",
    receiverId: "1",
    countryName: "Japan",
    location: "Tokyo, Japan",
    latitude: 35.6762,
    longitude: 139.6503,
    greeting: "Konnichiwa!",
    text: "Die Stadt ist unglaublich – Neonlichter überall und das Essen ist der Wahnsinn. Wünschte du wärst hier!",
    image: "https://example.com/images/tokyo.jpg",
    createdAt: new Date("2024-11-10T14:23:00Z"),
    questId: 3,
    xp: 50,
    receiverAddress: { street: "Musterstraße 1", city: "Berlin", zip: "10115" },
    creator: { firstName: "Max", lastName: "Müller" },
    receiver: { firstName: "Anna", lastName: "Schmidt" },
  },
  {
    id: 2,
    creatorId: "1",
    receiverId: "2",
    countryName: "Portugal",
    location: "Lissabon, Portugal",
    latitude: 38.7169,
    longitude: -9.1395,
    greeting: "Olá!",
    text: "Die Straßenbahn hoch zur Burg ist schon etwas besonderes. Pastéis de nata jeden Morgen – ich komme nie wieder heim.",
    image: "https://example.com/images/lisbon.jpg",
    createdAt: new Date("2024-12-01T09:10:00Z"),
    questId: null,
    xp: 30,
    receiverAddress: { street: "Hauptweg 9", city: "München", zip: "80331" },
    creator: { firstName: "Anna", lastName: "Schmidt" },
    receiver: { firstName: "Max", lastName: "Müller" },
  },
  {
    id: 3,
    creatorId: "2",
    receiverId: null,
    countryName: "Australien",
    location: "Sydney, Australien",
    latitude: -33.8688,
    longitude: 151.2093,
    greeting: "G'day!",
    text: "Hab heute mein erstes Känguru in freier Wildbahn gesehen. Das Opernhaus ist noch beeindruckender als auf Fotos.",
    image: "https://example.com/images/sydney.jpg",
    createdAt: new Date("2025-01-15T18:45:00Z"),
    questId: 7,
    xp: 75,
    receiverAddress: null,
    creator: { firstName: "Max", lastName: "Müller" },
    receiver: null,
  },
];
