import { useEffect } from "react";
import { Link, useNavigate } from "react-router-dom";

export function ImprintPrivacy() {
  const navigate = useNavigate();

  const handleBack = () => {
    navigate(-1);
  };

  useEffect(() => {
    document.title = "Mia | Imprint & Privacy";
  }, []);

  return (
    <main className="left">
      <Link
        to="#"
        onClick={handleBack}
        className="StepBack"
        aria-label="go back"
      >
        <img src="./icons/arrow-back.svg" alt="" aria-hidden="true" />
      </Link>

      <div className="imprint-privacy-container">
        <Link
          to="#"
          onClick={handleBack}
          className="ImprintStepBack"
          aria-label="go back"
        >
          <img src="./icons/arrow-back.svg" alt="" aria-hidden="true" />
        </Link>
        <h1 className="text-l">Imprint & Privacy 📜</h1>
        <section className="imprint">
          <p>
            This website is a non-commercial student project of the MMT
            (Multimedia Technology) degree program at Salzburg University of
            Applied Sciences and is intended exclusively for academic purposes.
          </p>

          <div className="contact-info">
            <strong>Persons responsible for the content (jointly):</strong>
            <br />
            Julian Obermeier
            <br />
            Sonja Schorn
          </div>

          <div className="contact-info">
            <strong>Address:</strong>
            <br />
            Salzburg University of Applied Sciences
            <br />
            Urstein Süd 1
            <br />
            5412 Puch bei Hallein
            <br />
            Austria
          </div>

          <div className="contact-info">
            <strong>Contact:</strong>
            <br />
            <a href="mailto:jobermeier.mmt-b2024@fh-salzburg.ac.at">
              jobermeier.mmt-b2024@fh-salzburg.ac.at
            </a>
            <br />
            <a href="mailto:sschorn.mmt-b2024@fh-salzburg.ac.at">
              sschorn.mmt-b2024@fh-salzburg.ac.at
            </a>
          </div>
        </section>

        <section className="privacy-policy">
          <h2 className="text-m">Privacy Policy</h2>

          <div className="note">
            <p>
              <strong>Note:</strong> This website was created as part of a
              student project at Salzburg University of Applied Sciences and is
              intended exclusively for academic purposes. Last updated: 28 May
              2026.
            </p>
          </div>

          <h3 className="text-s">1. Controller</h3>
          <p>
            Jointly responsible (Art. 26 GDPR) for the processing of personal
            data on this website are Julian Obermeier and Sonja Schorn.
          </p>

          <h3 className="text-s">2. What data we collect and why</h3>

          <p>
            <strong>Account data.</strong> When you create an account we store:
            an internal user ID, your first name, last name, display name, email
            address, an XP (experience points) counter, an internal unsubscribe
            token, your email notification preference, and timestamps for
            creation and last update. For authentication we store either a
            hashed password or, if you set one up, your passkey credential
            information (public key, credential ID, device type, sign counter
            and related metadata). Legal basis: Art. 6 (1) (b) GDPR (performance
            of a contract / pre-contractual measures at your request).
          </p>

          <p>
            <strong>Session data.</strong> While you are signed in, our
            authentication library (better-auth) creates a session record
            containing a session token, your IP address, your user-agent string,
            and an expiry timestamp. This is used to keep you signed in and to
            protect against session hijacking. Sessions expire automatically.
            Legal basis: Art. 6 (1) (b) GDPR (login function) and Art. 6 (1) (f)
            GDPR (security of the service).
          </p>

          <p>
            <strong>Postcard content.</strong> When you create a postcard, we
            store the composed image, a greeting, the message text, your chosen
            sender location (country or city), a fictional receiver address
            generated by us, the achieved XP value, and a creation timestamp.
            Postcards are linked to you as the creator and, after delivery, to
            the recipient. Legal basis: Art. 6 (1) (b) GDPR.
          </p>

          <p>
            <strong>Image moderation hashes.</strong> For each postcard image we
            store a one-way cryptographic hash together with your user ID. This
            lets us avoid re-checking the same image twice and helps detect
            abusive patterns. The hash cannot be reversed into the original
            image. Legal basis: Art. 6 (1) (f) GDPR (protecting users from
            inappropriate content).
          </p>

          <p>
            <strong>Email content.</strong> Emails we send through our mail
            provider (Resend) contain your email address and your first name for
            the salutation. Postcard notification emails additionally include an
            unsubscribe link with a unique token that lets you turn off
            notifications without logging in. Password reset emails contain a
            single-use reset token. See section 5.
          </p>

          <h3 className="text-s">3. Hosting</h3>
          <p>
            The application runs on an in-house Dokploy server operated by
            Salzburg University of Applied Sciences (Urstein Süd 1, 5412 Puch
            bei Hallein, Austria), including a PostgreSQL database on the same
            machine. Apart from the session data described in section 2 (which
            is created by our authentication library), we do not log additional
            access data in our own application code. The underlying server and
            network infrastructure of the university may process technical
            access data (e.g. IP addresses, timestamps) for operating and
            securing the network; we have no insight into these logs. Legal
            basis: Art. 6 (1) (f) GDPR.
          </p>

          <h3 className="text-s">4. Cloudflare</h3>
          <p>
            The frontend domain <code>mia.jlaoemir.at</code> is proxied through
            Cloudflare (Cloudflare, Inc., 101 Townsend St, San Francisco, CA
            94107, USA). This means all requests to the frontend pass through
            Cloudflare's network. Cloudflare may set short-lived technical
            cookies (e.g. <code>__cf_bm</code> for bot management) and processes
            connection data such as your IP address for content delivery, DDoS
            mitigation and bot detection. Cloudflare is certified under the
            EU–US Data Privacy Framework, so transfers to the United States rely
            on the EU Commission's adequacy decision (Art. 45 GDPR).
            Cloudflare's privacy policy:{" "}
            <a
              href="https://www.cloudflare.com/privacypolicy/"
              target="_blank"
              rel="noopener noreferrer"
            >
              https://www.cloudflare.com/privacypolicy/
            </a>
            . Legal basis: Art. 6 (1) (f) GDPR (security and reliable
            operation).
          </p>
          <p>
            Our backend domain <code>api.mia.jlaoemir.at</code> uses Cloudflare
            for DNS resolution only and is not proxied; Cloudflare therefore
            only sees DNS lookups, not the contents of your requests.
          </p>

          <h3 className="text-s">5. Resend (email delivery)</h3>
          <p>
            We use Resend (Resend, Inc., 2261 Market Street #5039, San
            Francisco, CA 94114, USA) to send transactional emails: postcard
            arrival notifications, password reset emails and email verification.
            Transmitted to Resend are your email address, your first name (for
            the salutation), an unsubscribe token for postcard notifications,
            and, for password resets, a single-use reset token. You can opt out
            of email notifications at any time through the unsubscribe link in
            every email. Transactional messages such as password reset and email
            verification cannot be disabled, as they are required to operate
            your account. Resend is certified under the EU–US Data Privacy
            Framework, so transfers to the United States rely on the EU
            Commission's adequacy decision (Art. 45 GDPR). Resend's privacy
            policy:{" "}
            <a
              href="https://resend.com/legal/privacy-policy"
              target="_blank"
              rel="noopener noreferrer"
            >
              https://resend.com/legal/privacy-policy
            </a>
            . Legal basis: Art. 6 (1) (b) GDPR.
          </p>

          <h3 className="text-s">6. Sightengine (image moderation)</h3>
          <p>
            Every postcard image you submit is forwarded to Sightengine
            (Sightengine SAS, 16 rue Joubert, 75009 Paris, France) for automated
            moderation against not-safe-for-work and otherwise inappropriate
            content. We do not transmit your name, email or any other account
            information. Sightengine is processed within the European Union - no
            third-country transfer takes place. Sightengine's privacy policy:{" "}
            <a
              href="https://sightengine.com/privacy"
              target="_blank"
              rel="noopener noreferrer"
            >
              https://sightengine.com/privacy
            </a>
            . Legal basis: Art. 6 (1) (f) GDPR (protecting users from harmful
            content).
          </p>

          <h3 className="text-s">7. HaveIBeenPwned (password security)</h3>
          <p>
            When you sign up or change your password, we check whether your
            chosen password has appeared in known data breaches using the
            HaveIBeenPwned Pwned Passwords API (operated by Troy Hunt,
            Australia, and delivered via Cloudflare's edge network). We use the
            k-anonymity method: only the first five characters of the SHA-1 hash
            of your password are sent — never the password itself or your full
            hash. This prefix mathematically cannot be linked back to your
            password or to you personally. No personal data within the meaning
            of Art. 4 (1) GDPR is transferred. Legal basis: Art. 6 (1) (f) GDPR
            (account security).
          </p>

          <h3 className="text-s">8. OpenStreetMap & Leaflet</h3>
          <p>
            We use the open-source mapping library Leaflet to display
            interactive maps. The map tiles are loaded directly from the servers
            of the OpenStreetMap Foundation (St John's Innovation Centre, Cowley
            Road, Cambridge, CB4 0WS, United Kingdom). When you visit a page
            containing a map, your browser establishes a direct connection to
            these servers, transmitting your IP address and basic device
            information. The map does not request your geolocation; it only
            displays locations that you and other users have manually chosen
            when sending postcards. The United Kingdom is covered by an adequacy
            decision of the EU Commission. OpenStreetMap's privacy policy:{" "}
            <a
              href="https://wiki.osmfoundation.org/wiki/Privacy_Policy"
              target="_blank"
              rel="noopener noreferrer"
            >
              https://wiki.osmfoundation.org/wiki/Privacy_Policy
            </a>
            . Legal basis: Art. 6 (1) (f) GDPR.
          </p>

          <h3 className="text-s">9. Postcards and recipients</h3>
          <p>
            The purpose of Mia is to deliver postcards to other users of the
            platform. When a postcard you created is delivered, the recipient
            sees the image, the greeting, the message text and a fictional
            receiver address generated by us — no real address is shown. The
            recipient does not see your name, your email or your user ID.
          </p>
          <p>
            Please do not include personally identifying information about
            yourself or third parties in your postcard image or text, as this
            content will be shared with another user of the platform.
          </p>

          <h3 className="text-s">10. Cookies and local storage</h3>
          <p>
            <strong>Session cookie.</strong> better-auth sets a session cookie
            when you sign in. This cookie is strictly necessary to keep you
            logged in and to protect your session. Under § 165 (3) TKG 2021 and
            Art. 6 (1) (b) GDPR, strictly necessary cookies do not require
            consent.
          </p>
          <p>
            <strong>Local storage.</strong> We use your browser's local storage
            to temporarily save the postcard you are currently editing (image,
            message text and chosen sender country) so that you don't lose your
            work if you reload the page. better-auth additionally stores a
            client identifier in local storage for session handling. Local
            storage is not transmitted to any third party and you can clear it
            manually at any time through your browser settings.
          </p>
          <p>
            Cloudflare may additionally set short-lived technical cookies as
            described in section 4.
          </p>

          <h3 className="text-s">11. Data retention</h3>
          <p>
            Account data is retained for as long as your account exists. Session
            records expire automatically. Image moderation hashes are retained
            for as long as your Postcard is not sent. Postcards remain in our
            database for as long as the project is operated, so that recipients
            can continue to view postcards they have received. 
          </p>
          <p>
            If you request deletion of your account, we will remove your
            personal account data (including passkeys and image moderation
            hashes linked to your user ID) and disconnect the postcards you sent
            and received from your identity. The postcards themselves remain
            stored without a link to you so that other users can still view what
            they received. Please keep in mind that those images may still
            reveal your identity. If you also want the postcards you created to
            be deleted in full, please tell us so when you make your request and
            we will remove them. A request to delete postcards separately from
            an account deletion or especially after your account has been
            deleted is not possible and will be rejected. This is since they are
            no longer linked to you at that point.
          </p>

          <h3 className="text-s">12. Your rights</h3>
          <p>
            Under the GDPR, you have the right to obtain information about the
            personal data we hold about you (Art. 15), to have inaccurate data
            corrected (Art. 16), to have your data deleted (Art. 17), to
            restrict processing (Art. 18), to data portability (Art. 20), to
            object to processing based on our legitimate interests (Art. 21),
            and to withdraw any consent you have given with effect for the
            future (Art. 7 (3)). Because there is currently no self-service
            deletion button in your profile, please contact us at the email
            addresses below; we will process your request without undue delay.
          </p>
          <p>
            If you believe that your data protection rights have been infringed,
            you can lodge a complaint with the Austrian Data Protection
            Authority (Datenschutzbehörde, Barichgasse 40–42, 1030 Vienna,{" "}
            <a
              href="https://www.dsb.gv.at"
              target="_blank"
              rel="noopener noreferrer"
            >
              https://www.dsb.gv.at
            </a>
            ).
          </p>

          <h3 className="text-s">13. Data security</h3>
          <p>
            We protect your data with appropriate organizational and technical
            measures, including encrypted transport (HTTPS), hashed passwords,
            and access controls on the database. Despite these measures,
            transmission over the internet cannot be guaranteed to be completely
            secure, and we accept no liability for unauthorized access by third
            parties that is not attributable to us.
          </p>

          <h3 className="text-s">14. Data breach notification</h3>
          <p>
            We strive to identify data breaches early. Where a breach is likely
            to result in a risk to your rights and freedoms, we will notify you
            and the competent supervisory authority in accordance with Art. 33
            and Art. 34 GDPR.
          </p>

          <h3 className="text-s">15. Contact</h3>
          <p>
            For any data protection request — access, correction, deletion, data
            portability or to withdraw consent — please contact us:
          </p>
          <p>
            <strong>Julian Obermeier and Sonja Schorn</strong>
            <br />
            Urstein Süd 1, 5412 Puch bei Hallein, Austria
            <br />
            <a href="mailto:jobermeier.mmt-b2024@fh-salzburg.ac.at">
              jobermeier.mmt-b2024@fh-salzburg.ac.at
            </a>
            <br />
            <a href="mailto:sschorn.mmt-b2024@fh-salzburg.ac.at">
              sschorn.mmt-b2024@fh-salzburg.ac.at
            </a>
          </p>
        </section>
      </div>
    </main>
  );
}
